# Generated by Django 6.0.1 on 2026-01-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contactinquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
