# Generated by Django 6.0.1 on 2026-01-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_contactinquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stonetype',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stonetype',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stonetype',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stonetype',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stonetype',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stonetype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
