# Generated by Django 6.0.1 on 2026-01-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyinfo_address_az_companyinfo_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='address_az',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tagline_az',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tagline_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='stonetype',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='stonetype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='stonetype',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='stonetype',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='stonetype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='stonetype',
            name='name_ru',
        ),
    ]
