# Generated by Django 6.0.1 on 2026-02-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_update_about_content_defaults'),
        ('company', '0007_aboutpagecontent'),
    ]

    operations = [
    ]
