# Generated by Django 6.0.1 on 2026-02-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_merge_20260201_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='customer_icon',
            field=models.CharField(default='fas fa-handshake', help_text='Font Awesome icon class', max_length=50, verbose_name='Customer Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='delivery_icon',
            field=models.CharField(default='fas fa-clock', help_text='Font Awesome icon class', max_length=50, verbose_name='Delivery Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='equipment_icon',
            field=models.CharField(default='fas fa-cogs', help_text='Font Awesome icon class', max_length=50, verbose_name='Equipment Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='guarantee_icon',
            field=models.CharField(default='fas fa-shield-alt', help_text='Font Awesome icon class', max_length=50, verbose_name='Guarantee Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='mission_icon',
            field=models.CharField(default='fas fa-bullseye', help_text='Font Awesome icon class', max_length=50, verbose_name='Mission Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='quality_icon',
            field=models.CharField(default='fas fa-award', help_text='Font Awesome icon class', max_length=50, verbose_name='Quality Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='team_icon',
            field=models.CharField(default='fas fa-users', help_text='Font Awesome icon class', max_length=50, verbose_name='Team Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='vision_icon',
            field=models.CharField(default='fas fa-eye', help_text='Font Awesome icon class', max_length=50, verbose_name='Vision Icon'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_us_title',
            field=models.CharField(default='Why Choose Precision Gems?', max_length=200, verbose_name='Why Choose Us Title'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_us_title_az',
            field=models.CharField(default='Precision Gems\'i niyə seçməliyik?', max_length=200, null=True, verbose_name='Why Choose Us Title'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_us_title_en',
            field=models.CharField(default='Why Choose Precision Gems?', max_length=200, null=True, verbose_name='Why Choose Us Title'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_us_title_ru',
            field=models.CharField(default='Почему выбирают Precision Gems?', max_length=200, null=True, verbose_name='Why Choose Us Title'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='customer_description',
            field=models.CharField(default='Your satisfaction is our top priority', max_length=200, verbose_name='Customer Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='customer_description_az',
            field=models.CharField(default='Müştəri məmnuniyyəti bizim ən yüksək prioritetimizdir', max_length=200, null=True, verbose_name='Customer Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='customer_description_en',
            field=models.CharField(default='Your satisfaction is our top priority', max_length=200, null=True, verbose_name='Customer Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='customer_description_ru',
            field=models.CharField(default='Ваше удовлетворение - наш главный приоритет', max_length=200, null=True, verbose_name='Customer Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='delivery_description',
            field=models.CharField(default='On-time project completion guaranteed', max_length=200, verbose_name='Delivery Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='delivery_description_az',
            field=models.CharField(default='Layihələrin vaxtında tamamlanması zəmanət edilir', max_length=200, null=True, verbose_name='Delivery Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='delivery_description_en',
            field=models.CharField(default='On-time project completion guaranteed', max_length=200, null=True, verbose_name='Delivery Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='delivery_description_ru',
            field=models.CharField(default='Гарантированное завершение проектов в срок', max_length=200, null=True, verbose_name='Delivery Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='equipment_description',
            field=models.CharField(default='State-of-the-art technology for superior results', max_length=200, verbose_name='Equipment Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='equipment_description_az',
            field=models.CharField(default='Əla nəticələr üçün müasir texnologiyalar', max_length=200, null=True, verbose_name='Equipment Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='equipment_description_en',
            field=models.CharField(default='State-of-the-art technology for superior results', max_length=200, null=True, verbose_name='Equipment Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='equipment_description_ru',
            field=models.CharField(default='Современные технологии для превосходных результатов', max_length=200, null=True, verbose_name='Equipment Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='guarantee_description',
            field=models.CharField(default='We stand behind our work with confidence', max_length=200, verbose_name='Guarantee Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='guarantee_description_az',
            field=models.CharField(default='İşimizə tam etibar edirik', max_length=200, null=True, verbose_name='Guarantee Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='guarantee_description_en',
            field=models.CharField(default='We stand behind our work with confidence', max_length=200, null=True, verbose_name='Guarantee Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='guarantee_description_ru',
            field=models.CharField(default='Мы с уверенностью гарантируем нашу работу', max_length=200, null=True, verbose_name='Guarantee Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quality_description',
            field=models.CharField(default='Precision in every cut, perfection in every polish', max_length=200, verbose_name='Quality Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quality_description_az',
            field=models.CharField(default='Hər kəsikdə dəqiqlik, hər cilalamada mükəmməllik', max_length=200, null=True, verbose_name='Quality Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quality_description_en',
            field=models.CharField(default='Precision in every cut, perfection in every polish', max_length=200, null=True, verbose_name='Quality Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quality_description_ru',
            field=models.CharField(default='Точность в каждом срезе, совершенство в каждой полировке', max_length=200, null=True, verbose_name='Quality Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='team_description',
            field=models.CharField(default='Professional specialists with decades of experience', max_length=200, verbose_name='Team Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='team_description_az',
            field=models.CharField(default='Onillik təcrübəyə malik peşəkar mütəxəssislər', max_length=200, null=True, verbose_name='Team Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='team_description_en',
            field=models.CharField(default='Professional specialists with decades of experience', max_length=200, null=True, verbose_name='Team Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='team_description_ru',
            field=models.CharField(default='Профессиональные специалисты с десятилетиями опыта', max_length=200, null=True, verbose_name='Team Description'),
        ),
    ]