# Generated by Django 6.0.1 on 2026-02-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_aboutpagecontent_customer_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(help_text='e.g., "Monday - Friday" or "Saturday"', max_length=100, verbose_name='Day Label')),
                ('day_label_az', models.CharField(help_text='e.g., "Monday - Friday" or "Saturday"', max_length=100, null=True, verbose_name='Day Label')),
                ('day_label_en', models.CharField(help_text='e.g., "Monday - Friday" or "Saturday"', max_length=100, null=True, verbose_name='Day Label')),
                ('day_label_ru', models.CharField(help_text='e.g., "Monday - Friday" or "Saturday"', max_length=100, null=True, verbose_name='Day Label')),
                ('time_range', models.CharField(help_text='e.g., "8:00 AM - 6:00 PM" or "Closed"', max_length=100, verbose_name='Time Range')),
                ('time_range_az', models.CharField(help_text='e.g., "8:00 AM - 6:00 PM" or "Closed"', max_length=100, null=True, verbose_name='Time Range')),
                ('time_range_en', models.CharField(help_text='e.g., "8:00 AM - 6:00 PM" or "Closed"', max_length=100, null=True, verbose_name='Time Range')),
                ('time_range_ru', models.CharField(help_text='e.g., "8:00 AM - 6:00 PM" or "Closed"', max_length=100, null=True, verbose_name='Time Range')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is Closed')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_az', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('url_name', models.CharField(help_text='Django URL name (e.g., "home", "about")', max_length=100, verbose_name='URL Name')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (optional)', max_length=50, verbose_name='Icon')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Precision Gems Ltd.', max_length=200, verbose_name='Site Title')),
                ('site_title_az', models.CharField(default='Precision Gems Ltd.', max_length=200, null=True, verbose_name='Site Title')),
                ('site_title_en', models.CharField(default='Precision Gems Ltd.', max_length=200, null=True, verbose_name='Site Title')),
                ('site_title_ru', models.CharField(default='Precision Gems Ltd.', max_length=200, null=True, verbose_name='Site Title')),
                ('default_phone', models.CharField(default='+994501234567', max_length=20, verbose_name='Default Phone')),
                ('enable_contact_form', models.BooleanField(default=True, verbose_name='Enable Contact Form')),
                ('footer_text', models.CharField(blank=True, max_length=300, verbose_name='Footer Text')),
                ('footer_text_az', models.CharField(blank=True, max_length=300, null=True, verbose_name='Footer Text')),
                ('footer_text_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Footer Text')),
                ('footer_text_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Footer Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
