# Generated by Django 6.0.1 on 2026-02-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_businesshours_navigationitem_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Contact Us', max_length=200, verbose_name='Page Title')),
                ('page_subtitle', models.CharField(default='Get in touch with our expert team', max_length=300, verbose_name='Page Subtitle')),
                ('form_title', models.CharField(default='Send us a Message', max_length=200, verbose_name='Form Title')),
                ('contact_info_title', models.CharField(default='Contact Information', max_length=200, verbose_name='Contact Info Title')),
                ('send_message_button', models.CharField(default='Send Message', max_length=50, verbose_name='Send Message Button')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(default='Our Services', max_length=200, verbose_name='Services Title')),
                ('services_subtitle', models.CharField(default='Comprehensive stone processing solutions tailored to your needs', max_length=300, verbose_name='Services Subtitle')),
                ('stone_types_title', models.CharField(default='Stone Types We Work With', max_length=200, verbose_name='Stone Types Title')),
                ('stone_types_subtitle', models.CharField(default='Expert processing for various stone materials', max_length=300, verbose_name='Stone Types Subtitle')),
                ('cta_title', models.CharField(default='Ready to Transform Your Stone Materials?', max_length=200, verbose_name='CTA Title')),
                ('cta_subtitle', models.CharField(default='Contact us today for a free consultation and quote!', max_length=300, verbose_name='CTA Subtitle')),
                ('get_quote_button', models.CharField(default='Get Free Quote', max_length=50, verbose_name='Get Quote Button')),
                ('our_services_button', models.CharField(default='Our Services', max_length=50, verbose_name='Our Services Button')),
                ('view_all_services_button', models.CharField(default='View All Services', max_length=50, verbose_name='View All Services Button')),
                ('view_all_stones_button', models.CharField(default='View All Stone Types', max_length=50, verbose_name='View All Stones Button')),
                ('start_project_button', models.CharField(default='Start Your Project', max_length=50, verbose_name='Start Project Button')),
                ('call_now_button', models.CharField(default='Call Now', max_length=50, verbose_name='Call Now Button')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Our Services', max_length=200, verbose_name='Page Title')),
                ('page_subtitle', models.CharField(default='Comprehensive stone processing solutions for all your needs', max_length=300, verbose_name='Page Subtitle')),
                ('cta_title', models.CharField(default='Ready to Get Started?', max_length=200, verbose_name='CTA Title')),
                ('cta_subtitle', models.CharField(default='Contact us today to discuss your project requirements', max_length=300, verbose_name='CTA Subtitle')),
                ('consultation_button', models.CharField(default='Get Free Consultation', max_length=50, verbose_name='Consultation Button')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Services Page Content',
                'verbose_name_plural': 'Services Page Content',
            },
        ),
        migrations.CreateModel(
            name='StoneTypesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Stone Types We Work With', max_length=200, verbose_name='Page Title')),
                ('page_subtitle', models.CharField(default='Expert processing for various natural stone materials', max_length=300, verbose_name='Page Subtitle')),
                ('cta_title', models.CharField(default='Not Sure Which Stone is Right for You?', max_length=200, verbose_name='CTA Title')),
                ('cta_subtitle', models.CharField(default='Our experts can help you choose the perfect stone for your project', max_length=300, verbose_name='CTA Subtitle')),
                ('expert_advice_button', models.CharField(default='Get Expert Advice', max_length=50, verbose_name='Expert Advice Button')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Stone Types Page Content',
                'verbose_name_plural': 'Stone Types Page Content',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© 2024 Precision Gems Ltd. All rights reserved.', max_length=300, verbose_name='Copyright Text'),
        ),
    ]
