# Generated by Django 6.0.1 on 2026-02-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_contactpagecontent_homepagecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_title_az',
            field=models.CharField(default='Contact Information', max_length=200, null=True, verbose_name='Contact Info Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_title_en',
            field=models.CharField(default='Contact Information', max_length=200, null=True, verbose_name='Contact Info Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='contact_info_title_ru',
            field=models.CharField(default='Contact Information', max_length=200, null=True, verbose_name='Contact Info Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='form_title_az',
            field=models.CharField(default='Send us a Message', max_length=200, null=True, verbose_name='Form Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='form_title_en',
            field=models.CharField(default='Send us a Message', max_length=200, null=True, verbose_name='Form Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='form_title_ru',
            field=models.CharField(default='Send us a Message', max_length=200, null=True, verbose_name='Form Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='page_subtitle_az',
            field=models.CharField(default='Get in touch with our expert team', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='page_subtitle_en',
            field=models.CharField(default='Get in touch with our expert team', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='page_subtitle_ru',
            field=models.CharField(default='Get in touch with our expert team', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='page_title_az',
            field=models.CharField(default='Contact Us', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='page_title_en',
            field=models.CharField(default='Contact Us', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='page_title_ru',
            field=models.CharField(default='Contact Us', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='send_message_button_az',
            field=models.CharField(default='Send Message', max_length=50, null=True, verbose_name='Send Message Button'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='send_message_button_en',
            field=models.CharField(default='Send Message', max_length=50, null=True, verbose_name='Send Message Button'),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='send_message_button_ru',
            field=models.CharField(default='Send Message', max_length=50, null=True, verbose_name='Send Message Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='call_now_button_az',
            field=models.CharField(default='Call Now', max_length=50, null=True, verbose_name='Call Now Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='call_now_button_en',
            field=models.CharField(default='Call Now', max_length=50, null=True, verbose_name='Call Now Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='call_now_button_ru',
            field=models.CharField(default='Call Now', max_length=50, null=True, verbose_name='Call Now Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_subtitle_az',
            field=models.CharField(default='Contact us today for a free consultation and quote!', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_subtitle_en',
            field=models.CharField(default='Contact us today for a free consultation and quote!', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_subtitle_ru',
            field=models.CharField(default='Contact us today for a free consultation and quote!', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_title_az',
            field=models.CharField(default='Ready to Transform Your Stone Materials?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_title_en',
            field=models.CharField(default='Ready to Transform Your Stone Materials?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_title_ru',
            field=models.CharField(default='Ready to Transform Your Stone Materials?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='get_quote_button_az',
            field=models.CharField(default='Get Free Quote', max_length=50, null=True, verbose_name='Get Quote Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='get_quote_button_en',
            field=models.CharField(default='Get Free Quote', max_length=50, null=True, verbose_name='Get Quote Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='get_quote_button_ru',
            field=models.CharField(default='Get Free Quote', max_length=50, null=True, verbose_name='Get Quote Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='our_services_button_az',
            field=models.CharField(default='Our Services', max_length=50, null=True, verbose_name='Our Services Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='our_services_button_en',
            field=models.CharField(default='Our Services', max_length=50, null=True, verbose_name='Our Services Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='our_services_button_ru',
            field=models.CharField(default='Our Services', max_length=50, null=True, verbose_name='Our Services Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='services_subtitle_az',
            field=models.CharField(default='Comprehensive stone processing solutions tailored to your needs', max_length=300, null=True, verbose_name='Services Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='services_subtitle_en',
            field=models.CharField(default='Comprehensive stone processing solutions tailored to your needs', max_length=300, null=True, verbose_name='Services Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='services_subtitle_ru',
            field=models.CharField(default='Comprehensive stone processing solutions tailored to your needs', max_length=300, null=True, verbose_name='Services Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='services_title_az',
            field=models.CharField(default='Our Services', max_length=200, null=True, verbose_name='Services Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='services_title_en',
            field=models.CharField(default='Our Services', max_length=200, null=True, verbose_name='Services Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='services_title_ru',
            field=models.CharField(default='Our Services', max_length=200, null=True, verbose_name='Services Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='start_project_button_az',
            field=models.CharField(default='Start Your Project', max_length=50, null=True, verbose_name='Start Project Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='start_project_button_en',
            field=models.CharField(default='Start Your Project', max_length=50, null=True, verbose_name='Start Project Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='start_project_button_ru',
            field=models.CharField(default='Start Your Project', max_length=50, null=True, verbose_name='Start Project Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='stone_types_subtitle_az',
            field=models.CharField(default='Expert processing for various stone materials', max_length=300, null=True, verbose_name='Stone Types Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='stone_types_subtitle_en',
            field=models.CharField(default='Expert processing for various stone materials', max_length=300, null=True, verbose_name='Stone Types Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='stone_types_subtitle_ru',
            field=models.CharField(default='Expert processing for various stone materials', max_length=300, null=True, verbose_name='Stone Types Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='stone_types_title_az',
            field=models.CharField(default='Stone Types We Work With', max_length=200, null=True, verbose_name='Stone Types Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='stone_types_title_en',
            field=models.CharField(default='Stone Types We Work With', max_length=200, null=True, verbose_name='Stone Types Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='stone_types_title_ru',
            field=models.CharField(default='Stone Types We Work With', max_length=200, null=True, verbose_name='Stone Types Title'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='view_all_services_button_az',
            field=models.CharField(default='View All Services', max_length=50, null=True, verbose_name='View All Services Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='view_all_services_button_en',
            field=models.CharField(default='View All Services', max_length=50, null=True, verbose_name='View All Services Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='view_all_services_button_ru',
            field=models.CharField(default='View All Services', max_length=50, null=True, verbose_name='View All Services Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='view_all_stones_button_az',
            field=models.CharField(default='View All Stone Types', max_length=50, null=True, verbose_name='View All Stones Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='view_all_stones_button_en',
            field=models.CharField(default='View All Stone Types', max_length=50, null=True, verbose_name='View All Stones Button'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='view_all_stones_button_ru',
            field=models.CharField(default='View All Stone Types', max_length=50, null=True, verbose_name='View All Stones Button'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='consultation_button_az',
            field=models.CharField(default='Get Free Consultation', max_length=50, null=True, verbose_name='Consultation Button'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='consultation_button_en',
            field=models.CharField(default='Get Free Consultation', max_length=50, null=True, verbose_name='Consultation Button'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='consultation_button_ru',
            field=models.CharField(default='Get Free Consultation', max_length=50, null=True, verbose_name='Consultation Button'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='cta_subtitle_az',
            field=models.CharField(default='Contact us today to discuss your project requirements', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='cta_subtitle_en',
            field=models.CharField(default='Contact us today to discuss your project requirements', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='cta_subtitle_ru',
            field=models.CharField(default='Contact us today to discuss your project requirements', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='cta_title_az',
            field=models.CharField(default='Ready to Get Started?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='cta_title_en',
            field=models.CharField(default='Ready to Get Started?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='cta_title_ru',
            field=models.CharField(default='Ready to Get Started?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='page_subtitle_az',
            field=models.CharField(default='Comprehensive stone processing solutions for all your needs', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='page_subtitle_en',
            field=models.CharField(default='Comprehensive stone processing solutions for all your needs', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='page_subtitle_ru',
            field=models.CharField(default='Comprehensive stone processing solutions for all your needs', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='page_title_az',
            field=models.CharField(default='Our Services', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='page_title_en',
            field=models.CharField(default='Our Services', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='servicespagecontent',
            name='page_title_ru',
            field=models.CharField(default='Our Services', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_az',
            field=models.CharField(default='© 2024 Precision Gems Ltd. All rights reserved.', max_length=300, null=True, verbose_name='Copyright Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_en',
            field=models.CharField(default='© 2024 Precision Gems Ltd. All rights reserved.', max_length=300, null=True, verbose_name='Copyright Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_ru',
            field=models.CharField(default='© 2024 Precision Gems Ltd. All rights reserved.', max_length=300, null=True, verbose_name='Copyright Text'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='cta_subtitle_az',
            field=models.CharField(default='Our experts can help you choose the perfect stone for your project', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='cta_subtitle_en',
            field=models.CharField(default='Our experts can help you choose the perfect stone for your project', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='cta_subtitle_ru',
            field=models.CharField(default='Our experts can help you choose the perfect stone for your project', max_length=300, null=True, verbose_name='CTA Subtitle'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='cta_title_az',
            field=models.CharField(default='Not Sure Which Stone is Right for You?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='cta_title_en',
            field=models.CharField(default='Not Sure Which Stone is Right for You?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='cta_title_ru',
            field=models.CharField(default='Not Sure Which Stone is Right for You?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='expert_advice_button_az',
            field=models.CharField(default='Get Expert Advice', max_length=50, null=True, verbose_name='Expert Advice Button'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='expert_advice_button_en',
            field=models.CharField(default='Get Expert Advice', max_length=50, null=True, verbose_name='Expert Advice Button'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='expert_advice_button_ru',
            field=models.CharField(default='Get Expert Advice', max_length=50, null=True, verbose_name='Expert Advice Button'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='page_subtitle_az',
            field=models.CharField(default='Expert processing for various natural stone materials', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='page_subtitle_en',
            field=models.CharField(default='Expert processing for various natural stone materials', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='page_subtitle_ru',
            field=models.CharField(default='Expert processing for various natural stone materials', max_length=300, null=True, verbose_name='Page Subtitle'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='page_title_az',
            field=models.CharField(default='Stone Types We Work With', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='page_title_en',
            field=models.CharField(default='Stone Types We Work With', max_length=200, null=True, verbose_name='Page Title'),
        ),
        migrations.AddField(
            model_name='stonetypespagecontent',
            name='page_title_ru',
            field=models.CharField(default='Stone Types We Work With', max_length=200, null=True, verbose_name='Page Title'),
        ),
    ]
