# Generated by Django 6.0.1 on 2026-02-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_contactpagecontent_contact_info_title_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='customer_description_az',
            field=models.CharField(default='Your satisfaction is our top priority', max_length=200, null=True, verbose_name='Customer Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='customer_description_ru',
            field=models.CharField(default='Your satisfaction is our top priority', max_length=200, null=True, verbose_name='Customer Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='delivery_description_az',
            field=models.CharField(default='On-time project completion guaranteed', max_length=200, null=True, verbose_name='Delivery Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='delivery_description_ru',
            field=models.CharField(default='On-time project completion guaranteed', max_length=200, null=True, verbose_name='Delivery Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='equipment_description_az',
            field=models.CharField(default='State-of-the-art technology for superior results', max_length=200, null=True, verbose_name='Equipment Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='equipment_description_ru',
            field=models.CharField(default='State-of-the-art technology for superior results', max_length=200, null=True, verbose_name='Equipment Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='guarantee_description_az',
            field=models.CharField(default='We stand behind our work with confidence', max_length=200, null=True, verbose_name='Guarantee Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='guarantee_description_ru',
            field=models.CharField(default='We stand behind our work with confidence', max_length=200, null=True, verbose_name='Guarantee Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quality_description_az',
            field=models.CharField(default='Precision in every cut, perfection in every polish', max_length=200, null=True, verbose_name='Quality Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quality_description_ru',
            field=models.CharField(default='Precision in every cut, perfection in every polish', max_length=200, null=True, verbose_name='Quality Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='team_description_az',
            field=models.CharField(default='Professional specialists with decades of experience', max_length=200, null=True, verbose_name='Team Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='team_description_ru',
            field=models.CharField(default='Professional specialists with decades of experience', max_length=200, null=True, verbose_name='Team Description'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='why_choose_us_title_az',
            field=models.CharField(default='Why Choose Precision Gems?', max_length=200, null=True, verbose_name='Why Choose Us Title'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='why_choose_us_title_ru',
            field=models.CharField(default='Why Choose Precision Gems?', max_length=200, null=True, verbose_name='Why Choose Us Title'),
        ),
    ]
